"""openteam_cli -- OpenTeam CLI package."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Optional

from ._shared import (
    eprint,
    _load_config,
    _workspace_root_from_cfg,
    _detect_workspace_project_from_cwd,
)
from .config import cmd_config_init, cmd_config_add_profile, cmd_config_use, cmd_config_show
from .workspace import cmd_workspace_init, cmd_workspace_show, cmd_workspace_doctor, cmd_workspace_migrate
from .project import cmd_project_list, cmd_project_config_init, cmd_project_config_show, cmd_project_config_set, cmd_project_config_validate, cmd_project_agents_inject, _project_repl
from .status import cmd_status, cmd_focus, cmd_agents, cmd_tasks
from .panel import cmd_panel_show, cmd_panel_open, cmd_panel_health, cmd_panel_sync
from .cluster import cmd_cluster_status, cmd_cluster_qualify, cmd_node_add, cmd_node_join_script
from .hub import cmd_hub_init, cmd_hub_up, cmd_hub_down, cmd_hub_status, cmd_hub_logs, cmd_hub_migrate, cmd_hub_expose, cmd_hub_backup, cmd_hub_restore, cmd_hub_export_config, cmd_hub_push_config
from .team import cmd_team_list, cmd_team_run, cmd_team_watch, cmd_team_proposals, cmd_team_decide, cmd_team_discussions_sync, cmd_team_coding_run, cmd_team_coding_tasks, cmd_team_logs, cmd_team_bug_scan_live
from .requirements import cmd_req_add, cmd_req_import, cmd_req_list, cmd_req_conflicts, cmd_req_verify, cmd_req_rebuild, cmd_req_baseline_show, cmd_req_baseline_set_v2
from .misc import (
    cmd_chat, cmd_doctor, cmd_policy_check, cmd_db_migrate, cmd_approvals_list,
    cmd_prompt_compile, cmd_prompt_diff,
    cmd_metrics_check, cmd_metrics_analyze, cmd_metrics_bootstrap,
    cmd_audit_deterministic_gov, cmd_audit_execution_strategy, cmd_audit_reqv3_locks,
    cmd_daemon_start, cmd_daemon_stop, cmd_daemon_status,
    cmd_repo_create,
    cmd_task_new, cmd_task_close, cmd_task_ship, cmd_task_resume,
    cmd_improvement_targets, cmd_improvement_target_add,
    cmd_openclaw_status, cmd_openclaw_config, cmd_openclaw_test, cmd_openclaw_sweep,
)


def main(argv: Optional[list[str]] = None) -> int:
    argv = list(argv) if argv is not None else sys.argv[1:]

    # Project directory convenience mode
    if not argv:
        cfg: dict[str, Any] = {}
        try:
            cfg = _load_config()
        except Exception:
            cfg = {}
        cur = Path.cwd().resolve()
        ws_candidates = [_workspace_root_from_cfg(cfg)]
        for p in [cur] + list(cur.parents):
            if p.name == "workspace":
                ws_candidates.append(p)
        seen: set[str] = set()
        for ws in ws_candidates:
            k = str(ws.resolve())
            if k in seen:
                continue
            seen.add(k)
            try:
                pid = _detect_workspace_project_from_cwd(ws, cwd=cur)
            except Exception:
                continue
            if pid:
                tmp = argparse.Namespace(profile=None, workspace_root=str(ws))
                try:
                    return int(_project_repl(tmp, project_id=pid))
                except Exception as e:
                    eprint(f"ERROR: {e}")
                    return 2

    p = argparse.ArgumentParser(prog="openteam", description="OpenTeam CLI (Control Plane client)")
    p.add_argument("--profile", help="profile name (from ~/.openteam/config.toml)")
    p.add_argument("--workspace-root", help="override workspace root (default: ~/.openteam/workspace or config)")

    sp = p.add_subparsers(dest="cmd", required=True)

    # config
    cfg_p = sp.add_parser("config")
    cfg_sp = cfg_p.add_subparsers(dest="subcmd", required=True)
    cfg_sp.add_parser("init").set_defaults(fn=cmd_config_init)
    ap = cfg_sp.add_parser("add-profile")
    ap.add_argument("name")
    ap.add_argument("base_url")
    ap.add_argument("--default-project-id")
    ap.set_defaults(fn=cmd_config_add_profile)
    up = cfg_sp.add_parser("use")
    up.add_argument("name")
    up.set_defaults(fn=cmd_config_use)
    cfg_sp.add_parser("show").set_defaults(fn=cmd_config_show)

    # workspace
    ws = sp.add_parser("workspace", help="Local Workspace (project truth sources live outside the repo)")
    ws_sp = ws.add_subparsers(dest="subcmd", required=True)
    wi = ws_sp.add_parser("init", help="Initialize workspace directories (idempotent)")
    wi.add_argument("--path", help="workspace root path (default from config)")
    wi.set_defaults(fn=cmd_workspace_init)
    ws_sp.add_parser("show", help="Show workspace root and project summary").set_defaults(fn=cmd_workspace_show)
    ws_sp.add_parser("doctor", help="Validate workspace structure and permissions").set_defaults(fn=cmd_workspace_doctor)
    wm = ws_sp.add_parser("migrate", help="Migrate legacy project artifacts out of the openteam repo (default dry-run)")
    wm.add_argument("--from-repo", action="store_true", help="scan current openteam repo for legacy project artifacts")
    wm.add_argument("--dry-run", action="store_true", help="plan only (default)")
    wm.add_argument("--force", action="store_true", help="apply moves (high risk; requires your approval)")
    wm.add_argument("--yes", action="store_true", help="skip interactive confirmation (still high risk)")
    wm.set_defaults(fn=cmd_workspace_migrate)

    # projects (workspace)
    pr = sp.add_parser("project", help="Workspace projects")
    pr_sp = pr.add_subparsers(dest="subcmd", required=True)
    pr_sp.add_parser("list", help="List projects under workspace").set_defaults(fn=cmd_project_list)

    pcfg = pr_sp.add_parser("config", help="Project config (Workspace-local; schema-validated)")
    pcfg_sp = pcfg.add_subparsers(dest="config_cmd", required=True)
    pci = pcfg_sp.add_parser("init", help="Create default project.yaml if missing (idempotent)")
    pci.add_argument("--project", required=True)
    pci.add_argument("--dry-run", action="store_true")
    pci.set_defaults(fn=cmd_project_config_init)
    pcs = pcfg_sp.add_parser("show", help="Show project.yaml")
    pcs.add_argument("--project", required=True)
    pcs.set_defaults(fn=cmd_project_config_show)
    pset = pcfg_sp.add_parser("set", help="Set a config key (dot-path) and validate schema")
    pset.add_argument("--project", required=True)
    pset.add_argument("--key", required=True)
    pset.add_argument("--value", required=True)
    pset.add_argument("--dry-run", action="store_true")
    pset.set_defaults(fn=cmd_project_config_set)
    pv = pcfg_sp.add_parser("validate", help="Validate project.yaml against schema")
    pv.add_argument("--project", required=True)
    pv.set_defaults(fn=cmd_project_config_validate)

    pag = pr_sp.add_parser("agents", help="Project repo AGENTS.md (Team-OS manual injection)")
    pag_sp = pag.add_subparsers(dest="agents_cmd", required=True)
    pinj = pag_sp.add_parser("inject", help="Inject/Update Team-OS manual block into project repo AGENTS.md")
    pinj.add_argument("--project", required=True)
    pinj.add_argument("--repo-path", dest="repo_path", help="override project repo path")
    pinj.add_argument("--dry-run", action="store_true")
    pinj.set_defaults(fn=cmd_project_agents_inject)

    st = sp.add_parser("status")
    st.add_argument("--project")
    st.add_argument("--workstream")
    st.add_argument("--all-decisions", action="store_true")
    st.set_defaults(fn=cmd_status)

    fc = sp.add_parser("focus")
    fc.add_argument("--set")
    fc.set_defaults(fn=cmd_focus)

    ag = sp.add_parser("agents")
    ag.add_argument("--all", action="store_true")
    ag.add_argument("--project")
    ag.add_argument("--workstream")
    ag.add_argument("--state")
    ag.add_argument("--role")
    ag.set_defaults(fn=cmd_agents)

    tk = sp.add_parser("tasks")
    tk.add_argument("--all", action="store_true")
    tk.add_argument("--project")
    tk.add_argument("--workstream")
    tk.add_argument("--state")
    tk.add_argument("--limit", type=int, default=50)
    tk.add_argument("--offset", type=int, default=0)
    tk.set_defaults(fn=cmd_tasks)

    pn = sp.add_parser("panel", help="GitHub Projects panel (view layer)")
    pn_sp = pn.add_subparsers(dest="subcmd", required=True)
    pshow = pn_sp.add_parser("show")
    pshow.add_argument("--project")
    pshow.set_defaults(fn=cmd_panel_show)
    popen = pn_sp.add_parser("open")
    popen.add_argument("--project")
    popen.set_defaults(fn=cmd_panel_open)
    phealth = pn_sp.add_parser("health")
    phealth.add_argument("--project")
    phealth.set_defaults(fn=cmd_panel_health)
    ps = pn_sp.add_parser("sync")
    ps.add_argument("--project")
    ps.add_argument("--full", action="store_true")
    ps.add_argument("--dry-run", action="store_true")
    ps.set_defaults(fn=cmd_panel_sync)

    cl = sp.add_parser("cluster", help="Multi-node cluster status (Brain/Assistant)")
    cl_sp = cl.add_subparsers(dest="subcmd", required=True)
    cl_sp.add_parser("status").set_defaults(fn=cmd_cluster_status)
    cl_sp.add_parser("qualify").set_defaults(fn=cmd_cluster_qualify)

    nd = sp.add_parser("node", help="Cluster node operations")
    nd_sp = nd.add_subparsers(dest="subcmd", required=True)
    na = nd_sp.add_parser("add", help="Bootstrap a remote node via SSH (default: dry-run)")
    na.add_argument("--host", required=True)
    na.add_argument("--user", required=True)
    na.add_argument("--ssh-key")
    na.add_argument("--password-stdin", action="store_true")
    na.add_argument("--cluster-repo", required=True)
    na.add_argument("--brain-base-url")
    na.add_argument("--role", default="auto")
    na.add_argument("--capabilities", default="")
    na.add_argument("--tags", default="")
    na.add_argument("--push-hub-config", action="store_true")
    na.add_argument("--hub-host", default="")
    na.add_argument("--remote-env-path", default="~/.openteam/node.env")
    na.add_argument("--execute", action="store_true")
    na.set_defaults(fn=cmd_node_add)
    nj = nd_sp.add_parser("join-script")
    nj.add_argument("--cluster-repo", required=True)
    nj.add_argument("--brain-base-url")
    nj.add_argument("--role", default="auto")
    nj.add_argument("--capabilities", default="")
    nj.add_argument("--tags", default="")
    nj.set_defaults(fn=cmd_node_join_script)

    hb = sp.add_parser("hub", help="Local/central Hub operations (Postgres + Redis)")
    hb_sp = hb.add_subparsers(dest="subcmd", required=True)
    hinit = hb_sp.add_parser("init")
    hinit.add_argument("--pg-port", type=int, default=5432)
    hinit.add_argument("--redis-port", type=int, default=6379)
    hinit.set_defaults(fn=cmd_hub_init)
    hb_sp.add_parser("up").set_defaults(fn=cmd_hub_up)
    hb_sp.add_parser("down").set_defaults(fn=cmd_hub_down)
    hb_sp.add_parser("status").set_defaults(fn=cmd_hub_status)
    hlogs = hb_sp.add_parser("logs")
    hlogs.add_argument("--service", choices=["postgres", "redis"], default="")
    hlogs.add_argument("--tail", type=int, default=200)
    hlogs.set_defaults(fn=cmd_hub_logs)
    hb_sp.add_parser("migrate").set_defaults(fn=cmd_hub_migrate)
    hexp = hb_sp.add_parser("expose")
    hexp.add_argument("--bind-ip", required=True)
    hexp.add_argument("--allow-cidrs", required=True)
    hexp.add_argument("--open-redis", action="store_true")
    hexp.set_defaults(fn=cmd_hub_expose)
    hbak = hb_sp.add_parser("backup")
    hbak.add_argument("--output", default="")
    hbak.set_defaults(fn=cmd_hub_backup)
    hres = hb_sp.add_parser("restore")
    hres.add_argument("--file", required=True)
    hres.set_defaults(fn=cmd_hub_restore)
    hec = hb_sp.add_parser("export-config")
    hec.add_argument("--format", choices=["env", "yaml"], default="env")
    hec.set_defaults(fn=cmd_hub_export_config)
    hpc = hb_sp.add_parser("push-config")
    hpc.add_argument("--host", required=True)
    hpc.add_argument("--user", required=True)
    hpc.add_argument("--ssh-key", default="")
    hpc.add_argument("--password-stdin", action="store_true")
    hpc.add_argument("--hub-host", default="")
    hpc.add_argument("--remote-env-path", default="~/.openteam/node.env")
    hpc.set_defaults(fn=cmd_hub_push_config)

    rp = sp.add_parser("repo", help="Repo operations (GitHub)")
    rp_sp = rp.add_subparsers(dest="subcmd", required=True)
    rc = rp_sp.add_parser("create")
    rc.add_argument("--name", required=True)
    rc.add_argument("--org")
    rc_vis = rc.add_mutually_exclusive_group()
    rc_vis.add_argument("--public", action="store_true")
    rc_vis.add_argument("--private", action="store_true")
    rc.add_argument("--clone-dir")
    rc.add_argument("--approve", action="store_true")
    rc.set_defaults(fn=cmd_repo_create)

    ts = sp.add_parser("task", help="Task lifecycle commands")
    ts_sp = ts.add_subparsers(dest="subcmd", required=True)
    tn = ts_sp.add_parser("new")
    tn.add_argument("--title", required=True)
    tn.add_argument("--scope")
    tn.add_argument("--project")
    tn.add_argument("--workstreams")
    tn.add_argument("--risk-level", default="R1")
    tn.add_argument("--mode", default="auto")
    tn.add_argument("--dry-run", action="store_true")
    tn.set_defaults(fn=cmd_task_new)
    tc = ts_sp.add_parser("close")
    tc.add_argument("task_id")
    tc.add_argument("--scope")
    tc.add_argument("--skip-tests", action="store_true")
    tc.add_argument("--dry-run", action="store_true")
    tc.set_defaults(fn=cmd_task_close)
    tsh = ts_sp.add_parser("ship")
    tsh.add_argument("task_id")
    tsh.add_argument("--scope")
    tsh.add_argument("--summary")
    tsh.add_argument("--base", default="main")
    tsh.add_argument("--no-pr", action="store_true")
    tsh.add_argument("--dry-run", action="store_true")
    tsh.set_defaults(fn=cmd_task_ship)
    tr = ts_sp.add_parser("resume")
    tr.add_argument("--all", action="store_true")
    tr.add_argument("--task-id")
    tr.set_defaults(fn=cmd_task_resume)

    ch = sp.add_parser("chat")
    ch.add_argument("--project")
    ch.add_argument("--workstream")
    ch.add_argument("--run")
    ch.set_defaults(fn=cmd_chat)

    req = sp.add_parser("req")
    req_sp = req.add_subparsers(dest="subcmd", required=True)
    ra = req_sp.add_parser("add")
    ra.add_argument("text")
    ra.add_argument("--scope")
    ra.add_argument("--project")
    ra.add_argument("--workstream")
    ra.add_argument("--priority", default="P2")
    ra.add_argument("--rationale")
    ra.add_argument("--constraints", nargs="*")
    ra.add_argument("--acceptance", nargs="*")
    ra.add_argument("--source")
    ra.set_defaults(fn=cmd_req_add)
    ri = req_sp.add_parser("import")
    ri.add_argument("--file", required=True)
    ri.add_argument("--scope")
    ri.add_argument("--project")
    ri.add_argument("--workstream")
    ri.set_defaults(fn=cmd_req_import)
    rl = req_sp.add_parser("list")
    rl.add_argument("--scope")
    rl.add_argument("--project")
    rl.add_argument("--show-conflicts", action="store_true")
    rl.set_defaults(fn=cmd_req_list)
    rcon = req_sp.add_parser("conflicts")
    rcon.add_argument("--scope")
    rcon.add_argument("--project")
    rcon.set_defaults(fn=cmd_req_conflicts)
    rv = req_sp.add_parser("verify")
    rv.add_argument("--scope")
    rv.add_argument("--project")
    rv.set_defaults(fn=cmd_req_verify)
    rb = req_sp.add_parser("rebuild")
    rb.add_argument("--scope")
    rb.add_argument("--project")
    rb.set_defaults(fn=cmd_req_rebuild)
    rbase = req_sp.add_parser("baseline")
    rbase_sp = rbase.add_subparsers(dest="baseline_cmd", required=True)
    rbs = rbase_sp.add_parser("show")
    rbs.add_argument("--scope")
    rbs.add_argument("--project")
    rbs.add_argument("--max-chars", type=int, default=4000)
    rbs.set_defaults(fn=cmd_req_baseline_show)
    rb2 = rbase_sp.add_parser("set-v2")
    rb2.add_argument("text")
    rb2.add_argument("--reason", required=True)
    rb2.add_argument("--scope")
    rb2.add_argument("--project")
    rb2.set_defaults(fn=cmd_req_baseline_set_v2)

    pm = sp.add_parser("prompt", help="Prompt operations (deterministic pipelines)")
    pm_sp = pm.add_subparsers(dest="subcmd", required=True)
    pc2 = pm_sp.add_parser("compile")
    pc2.add_argument("--scope")
    pc2.add_argument("--project")
    pc2.add_argument("--dry-run", action="store_true")
    pc2.set_defaults(fn=cmd_prompt_compile)
    pb = pm_sp.add_parser("build")
    pb.add_argument("--scope")
    pb.add_argument("--project")
    pb.add_argument("--dry-run", action="store_true")
    pb.set_defaults(fn=cmd_prompt_compile)
    pd = pm_sp.add_parser("diff")
    pd.add_argument("--scope")
    pd.add_argument("--project")
    pd.set_defaults(fn=cmd_prompt_diff)

    mt = sp.add_parser("metrics", help="Telemetry/metrics checks and analysis (local truth source)")
    mt_sp = mt.add_subparsers(dest="subcmd", required=True)
    mc = mt_sp.add_parser("check")
    mc.add_argument("--quiet", action="store_true")
    mc.set_defaults(fn=cmd_metrics_check)
    ma = mt_sp.add_parser("analyze")
    ma.set_defaults(fn=cmd_metrics_analyze)
    mb = mt_sp.add_parser("bootstrap")
    mb.add_argument("--dry-run", action="store_true")
    mb.set_defaults(fn=cmd_metrics_bootstrap)

    pol = sp.add_parser("policy", help="Local policy checks (no remote writes)")
    pol_sp = pol.add_subparsers(dest="subcmd", required=True)
    polc = pol_sp.add_parser("check")
    polc.add_argument("--json", action="store_true")
    polc.add_argument("--quiet", action="store_true")
    polc.set_defaults(fn=cmd_policy_check)

    db = sp.add_parser("db", help="Postgres DB (migrations)")
    db_sp = db.add_subparsers(dest="subcmd", required=True)
    dmig = db_sp.add_parser("migrate")
    dmig.add_argument("--db-url")
    dmig.add_argument("--dry-run", action="store_true")
    dmig.set_defaults(fn=cmd_db_migrate)

    apv = sp.add_parser("approvals")
    apv_sp = apv.add_subparsers(dest="subcmd", required=True)
    al = apv_sp.add_parser("list")
    al.add_argument("--limit", type=int, default=50)
    al.set_defaults(fn=cmd_approvals_list)

    au = sp.add_parser("audit", help="Deterministic audit generators (local-only)")
    au_sp = au.add_subparsers(dest="subcmd", required=True)
    dg = au_sp.add_parser("deterministic-gov")
    dg.add_argument("--out")
    dg.set_defaults(fn=cmd_audit_deterministic_gov)
    es = au_sp.add_parser("execution-strategy")
    es.add_argument("--out")
    es.set_defaults(fn=cmd_audit_execution_strategy)
    rl2 = au_sp.add_parser("reqv3-locks")
    rl2.add_argument("--out")
    rl2.add_argument("--project-id", dest="project_id", default="audit-e2e")
    rl2.add_argument("--skip-team", action="store_true")
    rl2.add_argument("--skip-db", action="store_true")
    rl2.set_defaults(fn=cmd_audit_reqv3_locks)

    sp.add_parser("doctor").set_defaults(fn=cmd_doctor)

    dm = sp.add_parser("daemon", help="Legacy daemon commands (team daemon removed)")
    dm_sp = dm.add_subparsers(dest="subcmd", required=True)
    ds = dm_sp.add_parser("start")
    ds.add_argument("--foreground", action="store_true")
    ds.set_defaults(fn=cmd_daemon_start)
    dx = dm_sp.add_parser("stop")
    dx.set_defaults(fn=cmd_daemon_stop)
    dy = dm_sp.add_parser("status")
    dy.set_defaults(fn=cmd_daemon_status)

    tm = sp.add_parser("team", help="Generic team operations")
    tm_sp = tm.add_subparsers(dest="team_cmd", required=True)
    tl = tm_sp.add_parser("list")
    tl.add_argument("--json", action="store_true")
    tl.set_defaults(fn=cmd_team_list)

    trn = tm_sp.add_parser("run")
    trn.add_argument("--team-id", required=True)
    trn.add_argument("--project")
    trn.add_argument("--workstream", default="general")
    trn.add_argument("--objective", default="")
    trn.add_argument("--target-id", default="")
    trn.add_argument("--repo-path", default="")
    trn.add_argument("--repo-url", default="")
    trn.add_argument("--repo-locator", default="")
    trn.add_argument("--dry-run", action="store_true")
    trn.add_argument("--force", action="store_true")
    trn.add_argument("--quiet", action="store_true")
    trn.set_defaults(fn=cmd_team_run)

    tw = tm_sp.add_parser("watch")
    tw.add_argument("--team-id", required=True)
    tw.add_argument("--run-id", default="")
    tw.add_argument("--project-id", default="")
    tw.add_argument("--timeout", type=int, default=3600)
    tw.add_argument("--json", action="store_true")
    tw.set_defaults(fn=cmd_team_watch)

    tp = tm_sp.add_parser("proposals")
    tp.add_argument("--team-id", required=True)
    tp.add_argument("--target-id", default="")
    tp.add_argument("--project-id", default="")
    tp.add_argument("--lane", default="")
    tp.add_argument("--status", default="")
    tp.add_argument("--json", action="store_true")
    tp.set_defaults(fn=cmd_team_proposals)

    td = tm_sp.add_parser("decide")
    td.add_argument("--team-id", required=True)
    td.add_argument("proposal_id")
    td.add_argument("action", choices=["approve", "reject", "hold"])
    td.add_argument("--title", default="")
    td.add_argument("--summary", default="")
    td.add_argument("--version-bump", default="")
    td.add_argument("--json", action="store_true")
    td.set_defaults(fn=cmd_team_decide)

    tsy = tm_sp.add_parser("discussions-sync")
    tsy.add_argument("--team-id", required=True)
    tsy.add_argument("--json", action="store_true")
    tsy.set_defaults(fn=cmd_team_discussions_sync)

    tcode = tm_sp.add_parser("coding")
    tc_sp = tcode.add_subparsers(dest="team_coding_cmd", required=True)
    tcr = tc_sp.add_parser("run")
    tcr.add_argument("--team-id", required=True)
    tcr.add_argument("--project")
    tcr.add_argument("--target-id", default="")
    tcr.add_argument("--task-id", default="")
    tcr.add_argument("--dry-run", action="store_true")
    tcr.add_argument("--force", action="store_true")
    tcr.add_argument("--concurrency", type=int, default=10)
    tcr.add_argument("--json", action="store_true")
    tcr.set_defaults(fn=cmd_team_coding_run)
    tct = tc_sp.add_parser("tasks")
    tct.add_argument("--team-id", required=True)
    tct.add_argument("--project")
    tct.add_argument("--target-id", default="")
    tct.add_argument("--status", default="")
    tct.add_argument("--json", action="store_true")
    tct.set_defaults(fn=cmd_team_coding_tasks)

    tlg = tm_sp.add_parser("logs")
    tlg.add_argument("--team-id", required=True)
    tlg.add_argument("--run-id", default="")
    tlg.add_argument("--limit", type=int, default=200)
    tlg.add_argument("--json", action="store_true")
    tlg.set_defaults(fn=cmd_team_logs)

    tbl = tm_sp.add_parser("bug-scan-live")
    tbl.add_argument("--team-id", required=True)
    tbl.add_argument("--target-id", required=True)
    tbl.add_argument("--project-id", default="")
    tbl.add_argument("--container", default="")
    tbl.add_argument("--json", action="store_true")
    tbl.set_defaults(fn=cmd_team_bug_scan_live)

    tgt = sp.add_parser("improvement-targets")
    tgt.add_argument("--project-id", default="")
    tgt.add_argument("--enabled-only", action="store_true")
    tgt.add_argument("--json", action="store_true")
    tgt.set_defaults(fn=cmd_improvement_targets)

    tga = sp.add_parser("improvement-target-add")
    tga.add_argument("--target-id", default="")
    tga.add_argument("--display-name", default="")
    tga.add_argument("--repo-path", default="")
    tga.add_argument("--repo-url", default="")
    tga.add_argument("--repo-locator", default="")
    tga.add_argument("--default-branch", default="")
    tga.add_argument("--disable", action="store_true")
    tga.add_argument("--auto-discovery", action="store_true")
    tga.add_argument("--auto-delivery", action="store_true")
    tga.add_argument("--ship-enabled", action="store_true")
    tga.add_argument("--workstream", default="general")
    tga.add_argument("--json", action="store_true")
    tga.set_defaults(fn=cmd_improvement_target_add)

    ocs = sp.add_parser("openclaw-status")
    ocs.add_argument("--json", action="store_true")
    ocs.set_defaults(fn=cmd_openclaw_status)

    occ = sp.add_parser("openclaw-config")
    occ.add_argument("--enable", action="store_true")
    occ.add_argument("--disable", action="store_true")
    occ.add_argument("--channel", default="")
    occ.add_argument("--target", default="")
    occ.add_argument("--gateway-mode", default="")
    occ.add_argument("--gateway-url", default="")
    occ.add_argument("--gateway-token", default="")
    occ.add_argument("--gateway-password", default="")
    occ.add_argument("--gateway-transport", default="")
    occ.add_argument("--gateway-state-dir", default="")
    occ.add_argument("--allow-insecure-private-ws", action="store_true")
    occ.add_argument("--disallow-insecure-private-ws", action="store_true")
    occ.add_argument("--path", action="append", default=[])
    occ.add_argument("--event-type", action="append", default=[])
    occ.add_argument("--exclude-event-type", action="append", default=[])
    occ.add_argument("--message-prefix", default="")
    occ.add_argument("--json", action="store_true")
    occ.set_defaults(fn=cmd_openclaw_config)

    oct_p = sp.add_parser("openclaw-test")
    oct_p.add_argument("--message", default="OpenTeam OpenClaw test message")
    oct_p.add_argument("--channel", default="")
    oct_p.add_argument("--target", default="")
    oct_p.add_argument("--path", default="")
    oct_p.add_argument("--dry-run", action="store_true")
    oct_p.add_argument("--json", action="store_true")
    oct_p.set_defaults(fn=cmd_openclaw_test)

    ocsw = sp.add_parser("openclaw-sweep")
    ocsw.add_argument("--dry-run", action="store_true")
    ocsw.add_argument("--limit", type=int, default=100)
    ocsw.add_argument("--json", action="store_true")
    ocsw.set_defaults(fn=cmd_openclaw_sweep)

    args = p.parse_args(argv)
    try:
        args.fn(args)
        return 0
    except Exception as e:
        eprint(f"ERROR: {e}")
        return 2
